apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: example1 
  labels: 
    app: example1
spec:   
  replicas: 2 
  selector: 
    matchLabels: 
      app: example1 
  template: 
    metadata: 
      labels: 
        app: example1 
    spec: 
      containers: 
      - name: example1 
        image: csagan/example1:latest 
        ports: 
        - containerPort: 9090
